### ISSUE TITLE
rename package so that it doenst mix with parent repo

### ISSUE THREAD

**Issue by acognigni-evotecnia** [HaylLtd/cordova-plugin-background-geolocation#106]
**Is your feature request related to a problem? Please describe.**
Ive just spent a really long time not understanding why it ionic/cordova kept telling me that the plugin i was trying to remove was not added. 
turns out to remove the old plugin i was taking you add command and replacing it with rm but since the order of the words changed
i also tried doing the oposite. i went to the ionic docs copy pasted their recommended install script and removed the autoh assuming it you pick up yours 

**Describe the solution you'd like**
a rename of the project in the repos so something move obvios like 'https://github.com/HarelM/cordova-plugin-background-geolocation-sdk31'

**Comment by HarelM** [comment]
I've tried to open an issue for the ionic docs, but nothing happened there, so I'm unable to fix this.
Regarding the name, is not specific to android etc so I don't have a better general name.
I also don't want to create a new package and deprecate this one.
Bottom line, changing the name will do more harm than good I believe...
Sorry...

**Comment by acognigni-evotecnia** [comment]
can you maybe add something in the readme?

**Comment by HarelM** [comment]
Feel free to send a PR :-)

**Comment by acognigni-evotecnia** [comment]
Will do
