### ISSUE TITLE
Error in android after updating the plugin

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#110]
**Describe the bug**
i updated the plugin to latest version and i got a warning in ios and error in android

**To Reproduce**
update the plugin to latest
**Expected behavior**

**Screenshots**

src/main/java/com/marianhello/bgloc/provider/DistanceFilterLocationProvider.java:89: error: cannot find symbol
            ? 0 | PendingIntent.FLAG_MUTABLE
                               ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

**Desktop (please complete the following information):**
src/main/java/com/marianhello/bgloc/provider/DistanceFilterLocationProvider.java:89: error: cannot find symbol
            ? 0 | PendingIntent.FLAG_MUTABLE
                               ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

**Smartphone (please complete the following information):**

**Additional context**
    <preference name="android-minSdkVersion" value="27" />
    <preference name="android-compileSdkVersion" value="27" />
    <preference name="android-targetSdkVersion" value="30" />
this is the sdk versions i used

**Comment by HarelM** [comment]
You probably need to change minSdk for android or continue using the old version.
Please elaborate on iOS, it is unclear what problems you have...

**Comment by ivinantony** [comment]
what should be the minSdk version to use?. i tried 30 but still the error

**Comment by HarelM** [comment]
What's your current configuring of min sdk and target sdk?

**Comment by ivinantony** [comment]
android-minSdkVersion =27
  android-compileSdkVersion=27
android-targetSdkVersion=30

**Comment by ivinantony** [comment]
but i changed it to 30 but still the same

**Comment by HarelM** [comment]
You'll need to open android studio and figure this out I guess.
Can you try 31 or 32?
I have no idea what's wrong. I know that I'm able to use this version and that is compiles well...

**Comment by ivinantony** [comment]
hi any updates or @HarelM can you provide me your config values

**Comment by ivinantony** [comment]
Still i am facing the same issue so i am not able to update the plugin

**Comment by HarelM** [comment]
https://github.com/IsraelHikingMap/Site/blob/fbd13035498b7654603d0f9331b65e6a1d4c0519/IsraelHiking.Web/src/application/services/geo-location.service.ts

I recently migrated to capacitor and the geolocation plugin of the community.
But the linked code is from the time I used this plugin.
