### ISSUE TITLE
Android Platform 10.1.2 - Build failed for Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0

### ISSUE THREAD

**Issue by FranGhe** [HaylLtd/cordova-plugin-background-geolocation#113]
Just 1 month ago I have published my first App on PlayStore using cordova-plugin-mauron85-background-geolocation

Now I have to fix small bugs, but when I start the build it fails... searching the solution on the web I found this topic that match with mine:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/766

Following the suggestion I have decided to remove that plugin and add your... but now I have now another issue... When I make the build it fail with this message:
```
Execution failed for task ':app:compileDebugJavaWithJavac'
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0
```
 if I remove your plugin the build is successful... I am absolutely sure that Gradle is installed when I install the Android platform... and it is out of my control.

These are my versions:
```
Cordova: 10.0.0
Android Platform: 10.1.2 
Gradle: 7.1.1
```

And these are my plugins:
```
cordova-background-geolocation-plugin 2.0.7
cordova-plugin-androidx-adapter 1.1.3
cordova-plugin-app-version 0.1.14
cordova-plugin-device 2.1.0
cordova-plugin-dialogs 2.0.2
cordova-plugin-file 7.0.0
cordova-plugin-geolocation 4.1.0
cordova-plugin-globalization 1.11.0
cordova-plugin-inappbrowser 5.0.0
cordova-plugin-insomnia 4.3.0
cordova-plugin-native-app-update 2.0.0
cordova-plugin-network-information 3.0.0
cordova-plugin-splashscreen 6.0.2
cordova-plugin-statusbar 3.0.0
```

How I can fix the issue?

**Comment by HarelM** [comment]
The following is not the issue:
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0`

Also note that you have both `cordova-plugin-geolocation` and `cordova-background-geolocation-plugin` which I think can cause issues.

I have this plugin in my app so I know it complies in Android and works well.
Please share more info.

Converting this to a discussion.
