### ISSUE TITLE
Can't create android build

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#120]
**Describe the bug**
plugin works on ios fine but when we create android build it gives error

**To Reproduce**
1. install the plugin in ionic 6 project
2. with cordova 10.0.0 or high or (9.1.0 above)
3. tried plugin versions ^2.0.4 and ^2.0.7

**Expected behavior**
It should create the build without error

**Screenshots**
<img width="1379" alt="Screenshot 2022-09-30 at 1 07 57 AM" src="https://user-images.githubusercontent.com/66516836/193126861-98b66c51-ca0f-4e87-8dd9-002212fd0d38.png">
The above error when i use compleSdk and targetSdk 29 below 

**Additional context**
if i use compleSdk and targetSdk 30 above the error is saying about android:export="true" but it still there in side the activity.
anyone who is having any idea please help me.

Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0,

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/Users/*****/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.14.0 (/usr/local/bin/node)
   npm               : 8.5.5
   OS                : macOS Monterey
   Xcode             : Xcode 14.0.1 Build version 14A400

**Comment by HarelM** [comment]
Immutable flag was added in version 2.0.6 so the above error can't happen in version 2.0.4.
See here:
https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/stable/CHANGELOG.md#v206-2022-08-02

Please make sure your environment is working as expected.

I know for a fact that this plugin can be build for both android 12 and before that as I have used it in my app for all those versions.

**Comment by ivinantony** [comment]
i found the issue that whenever i install the plugin with a specific version number, the plugin  version changes in package.json but in plugins folder inside the plugin it shows the latest version always. i dont know why it like that. i checked in a new project still same
