### ISSUE TITLE
cannot access zzbfm / class file for com.google.android.gms.internal.zzbfm not found - Ionic 6

### ISSUE THREAD

**Issue by seltix5** [HaylLtd/cordova-plugin-background-geolocation#128]
Hello,
I'm using Ionic 6 and it does not compile.
```
....android\capacitor-cordova-android-plugins\src\main\java\com\marianhello\bgloc\data\BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
```

**To Reproduce**
Compile Ionic 6 -> Android Studio

**Screenshots**
![image](https://user-images.githubusercontent.com/11258096/206959313-048d4796-f6c1-4bcb-84c0-388d877a7267.png)

**Desktop (please complete the following information):**
 - Windows 10

Thank you.

**Comment by HarelM** [comment]
Please add gms services in your build gradle like the following.
https://github.com/IsraelHikingMap/Site/blob/d89a3a5fc8f3ce12aa31f6bcd1d4b4499185f66f/IsraelHiking.Web/android/build.gradle#L11
