### ISSUE TITLE
How to access notificationIconLarge/notificationIconSmall?

### ISSUE THREAD

**Issue by veitbjarsch** [HaylLtd/cordova-plugin-background-geolocation#130]
Hi, I try to configure the notification icon. As the documentation stated I added the icon to `platforms/android/app/src/main/res/drawable/` but I could not find an example how I link this item in JS.

Currently I tried:
```
  notificationIconLarge: 'app_icon.png',
```
But this did not changed the icon. Which path do I need to add infront of the filename?

**Comment by HarelM** [comment]
I think you don't need the `.png`, you need the reduce resource ID.

**Comment by veitbjarsch** [comment]
Okay but how am I be able to get the resource ID in JS? Because there I configure the plugin. Or do I have the possibility to set this ID manually?

**Comment by HarelM** [comment]
Set it manually, usually the name of the image without any extension (not the number, the string).

**Comment by veitbjarsch** [comment]
Worked thank you. Sorry that I didn't wrote back till now
