### ISSUE TITLE
Default value "11+" for GOOGLE_PLAY_SERVICES_VERSION no longer supported

### ISSUE THREAD

**Issue by tsungweihsu** [HaylLtd/cordova-plugin-background-geolocation#136]
**Describe the bug**
Just starting from today, the app can no longer be built with the default version with error as below:
````
Could not resolve com.google.android.gms:play-services-location:11+
Failed to list versions for com.google.android.gms:play-services-location.
Unable to load Maven meta-data from https://maven.google.com/com/google/android/gms/play-services-location/maven-metadata.xml.
````
As I changed it directly in the source code from **11+** to **20.0.0**, the issue is resolved. I saw in the documentation, that it belongs to the configurable variables. But for the developers who use capacitor instead of cordova, the plugin is installed through npm, where these variables cannot be set during the installation.

**To Reproduce**
1. Install the plugin with npm
2. Use the plugin
3. Build the app

**Smartphone (please complete the following information):**
 - Pixel 3a with Android API 33

**Suggested Solution**
Update the default value from 11+ to 20.0.0 or the version which is still accessible from Google.

**Comment by HarelM** [comment]
I'm not sure I'm following. version 11 is still available in mvn:
https://mvnrepository.com/artifact/com.google.android.gms/play-services-location?repo=google
My build passed two hours ago:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/45958985/job/f9j4xpc7xlrsmy45
I'm not sure updating the version to 20 is a good idea as it will probably break compatibility with older SDKs...
Developers that use capacitor can change that in the capacitor gradle config file, that's the beauty of capacitor.

**Comment by tsungweihsu** [comment]
Hello Harel,
thanks for your quick replay. After some investigations into the problem, it was an internal server issue causing Google maven repository not reachable on our side. Thanks again for your response, I will close the issue.
