### ISSUE TITLE
Hidden or Change route notification when tap

### ISSUE THREAD

**Issue by santiagovasquez** [HaylLtd/cordova-plugin-background-geolocation#138]
Hello, first of all, thanks for creating and maintaining this great utility.

I'm using the "background-geolocation" and "background-mode" plugins. When the application goes into background mode, two notifications appear, but I only want to keep one active. I can easily hide the "background-mode" notification and keep the "background-geolocation" notification active. However, the "background-geolocation" notification only displays information about the application instead of opening it. I need it to open the application instead of just displaying the information.

I attach two images of what happens

The notification that active "background-geolocation"
<img width="373" alt="Screen Shot 2023-02-16 at 8 12 23 AM" src="https://user-images.githubusercontent.com/16017327/219377143-427b55ae-681c-4ac1-a36b-416513d5b190.png">

When I tap the notification, open the app info
<img width="377" alt="Screen Shot 2023-02-16 at 8 20 26 AM" src="https://user-images.githubusercontent.com/16017327/219376640-8578965b-72a2-461c-801b-139e48409538.png">

Any help thanks

**Comment by HarelM** [comment]
I had this issue as well, I think it has to do with the icon name or some thing, see here:
https://github.com/IsraelHikingMap/Site/issues/1613

**Comment by santiagovasquez** [comment]
Jaja OMG, the icon was the solution.
In my case I solved it by adding the next:

`BackgroundGeolocation.configure({`
            `notificationIconLarge: '@mipmap/ic_launcher',`
            `notificationIconSmall: '@mipmap/ic_launcher',`
            `...`
`})`

Thank you @HarelM ✊🏻
