### ISSUE TITLE
Can't switch from background to foreground mode while running

### ISSUE THREAD

**Issue by veitbjarsch** [HaylLtd/cordova-plugin-background-geolocation#139]
**Describe the bug**
Changing the startForeground config setting from false to true, while the service is running, doesn't apply the change.

**To Reproduce**
    
1. BackgroundGeolocation.configure({ 
      startForeground: true,
      notificationTitle: 'Some title',
      notificationText: 'Some text',
      notificationIconColor: '#30679a',
      notificationIconSmall: 'some_icon'
})
2. BackgroundGeolocation.start();
3. BackgroundGeolocation.configure({ startForeground: false });
4. Foreground notification does not appear

**Expected behavior**
Should display the foreground notification in the 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12

**Additional context**
The other way around it works without a problem (starting in foreground and switching to background mode.

**Comment by HarelM** [comment]
Sounds right, this isn't a dynamic property and should be applied when the service starts...
Why would you need to change it?

**Comment by veitbjarsch** [comment]
But the service restarts once I update the config. I also tried to stop and restart the geolocation, but it produces the same problem.

I need to change it because I only need the Foreground tracking if a specific progress is running other than that the tracking is only important when the app is in focus. So a Foreground message is not necessary.

Update: Okay now I realize that all of these functions are promise based if I don't add any handler to them. Good to know. This solved all of my problems and I can even cleanup my code.
