### ISSUE TITLE
Always send location in the background and without notification

### ISSUE THREAD

**Issue by josuelmm** [HaylLtd/cordova-plugin-background-geolocation#144]
I would like to continue sending the location even with the app closed, in the background. And without showing the notification, as the "Life360" application does, is it possible?

https://play.google.com/store/apps/details?id=com.life360.android.safetymapd

**Comment by HarelM** [comment]
You need special permissions from the Google store for that, which I don't think they give lightly.
I applied several times without getting any response...
So on theory, it might be possible, but generally speaking, it makes a lot more sense to notify the user the app is collecting data...

**Comment by josuelmm** [comment]
Excellent, thanks for your answer.
