### ISSUE TITLE
How to send Cookies with HTTP Location Posting

### ISSUE THREAD

**Issue by MazahirA** [HaylLtd/cordova-plugin-background-geolocation#165]
I'm using HTTP Location Posting to send data to my server. The customized data using postTemplate is successfully receiving to the server, but it's not sending cookies. 
How can we send cookies using the plugin?

**Comment by HarelM** [comment]
Using `httpHeaders`...?

**Comment by MazahirA** [comment]
By any mean. Using httpheaders or by customizing the plugin's java files like the 'HttpPostService.java' ?
The goal is to send  cookies along with the http location posting request.

**Comment by HarelM** [comment]
So use httpHeaders configuration option.

**Comment by MazahirA** [comment]
Can you explain how can we do that? 
Additionally, can we customize 'HttpPostService.java' file for this purpose as well?

**Comment by HarelM** [comment]
Feel free to read the docs:
https://haylltd.github.io/cordova-background-geolocation-plugin/api.html

You are welcome to do anything in a fork and use that, I'm not sure what you are suggesting here though...

**Comment by MazahirA** [comment]
Thank you for the help. 
In my scenario, I'm sending latitude and longitude to the server. But there's an authorization check before persisting data to the DB. That's why I need the cookie data to be send to the server when an HTTP Location Posting happens.  
Currently, it seems that the cookies aren't receiving to the server when I use HTTP Location Posting config. 
Therefore, I'm looking for ways to send cookies as well.

**Comment by MazahirA** [comment]
I have customized the 'HttpPostService.java' file, and it's sending cookies now.
