### ISSUE TITLE
INSTALL_FAILED_MISSING_SHARED_LIBRARY

### ISSUE THREAD

**Issue by bsprengelmeijer** [HaylLtd/cordova-plugin-background-geolocation#173]
When I add the plugin and run my app on a device with Android 5.1.1 I get the error [INSTALL_FAILED_MISSING_SHARED_LIBRARY]

It does work correctly on my other devices with Android 9.0 and up. 

[This thread ](https://stackoverflow.com/questions/1113088/install-failed-missing-shared-library-error-in-android) has a couple suggestions but none are applicable since those lines are not present in the Android manifest.

**Comment by HarelM** [comment]
Android 5.1.1 is not supported by the latest version, you might want to try earlier versions or the original fork of this repo.
