### ISSUE TITLE
Issue in closing of the line in "SQLiteOpenHelper.java" LocationEntry - missing ")" and ";" and possibly "+"

### ISSUE THREAD

**Issue by JensRunge** [HaylLtd/cordova-plugin-background-geolocation#180]
https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/1ad12f62540175c5e028960d0a38ce1120d639c6/android/common/src/main/java/com/marianhello/bgloc/data/sqlite/SQLiteOpenHelper.java#L120C1-L122C96

Hello Team,

there seem to be an issue in the SQLiteOpenHelper file (line 121):

CURRENTLY IS:
                alterSql.add("UPDATE " + LocationEntry.TABLE_NAME +
                                        " SET " + LocationEntry.COLUMN_NAME_VERTICAL_ACCURACY + "= -1,"
                                        LocationEntry.COLUMN_NAME_HAS_VERTICAL_ACCURACY + "= 0"

SHOULD BE?:
                alterSql.add("UPDATE " + LocationEntry.TABLE_NAME +
                                        " SET " + LocationEntry.COLUMN_NAME_VERTICAL_ACCURACY + "= -1,"+
                                        LocationEntry.COLUMN_NAME_HAS_VERTICAL_ACCURACY + "= 0");

Thanks and best regards
Jens

**Comment by HarelM** [comment]
Feel free to open a PR, I tend to think this code was added recently...

**Comment by JensRunge** [comment]
Unfortunately I never did this before. Anyone can help here?

**Comment by HarelM** [comment]
Might be fixed by: https://github.com/HaylLtd/cordova-background-geolocation-plugin/pull/182

**Comment by JensRunge** [comment]
Thanks a lot! 👍
