### ISSUE TITLE
Improve documentation around android background location posting

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-plugin-background-geolocation#29]
As it currently stands on Android, the plug-in does not execute the callback function in JS when the location changes while the app is in the background/the phone is locked.
The only way that the plug-in can communicate location changes to an API/server is through the http posting functionality.

This is different to the behaviour on iOS, where the callback function is called, allowing the app to post, even when in the background.

This needs to be communicated better in the documentation, as it is not clear.

**Comment by HarelM** [comment]
I fully agree, also I think it's important to emphasize the foreground service mode or maybe make it default as I believe if someone is using this plugin he will want the service to run as much as possible without getting killed by the os.

**Comment by RaddishIoW** [comment]
I have made it a bit clearer that you need to use the HTTP posting for background posts of location, but I'd like to make it a bit more prominent in the docs...
