### ISSUE TITLE
Make the tests run on every commit

### ISSUE THREAD

**Issue by HarelM** [HaylLtd/cordova-plugin-background-geolocation#30]
Currently there are tests in the repo which are not running. 
Also compilation should be done on every commit. 
Both are missing.
We need to investigate how the old CI was running in order to migrate it here, probably to github actions (assuming it have macos environment)

**Comment by HarelM** [comment]
For android running ./gradlew test seems to do the job of running the tests. I still need to understand how to integrate it into github and somehow look at the outcome.
For iOS I think the following is the direction we would like to go - using xcode from command line:
https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6

**Comment by HarelM** [comment]
Seems like this is more complicated than I thought.
When running ./gradlew build in the `android` folder (not the `common` folder) it fails to find CordovaLib, which is expected if the CordovaLib is not present (And I currently don't know how to get it, there's a comment about it in the [android readme file](https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/develop/android/README.md)).
I'll try to see if I can understand how to make it work as expected.
I posted a question in the Cordova Slack channel:
https://cordova.slack.com/archives/C068CHRJ5/p1620940215402200

**Comment by HarelM** [comment]
I've looked through the commands in the `config.yml` under `.circleci` folder and these are the commands:
got to `android` folder and executre:
`./gradlew androidDependencies`
`./gradlew test`
`./gradlew assembleDebug assembleAndroidTest`
The problem is that I can't understand how the CordovaLib folder gets filled with the relevant files.
I tried to fill it with content from another project and it failed to do step 3.
Not sure also how to get the `CordovaLib` folder in a CI environment, I couldn't find it on google and didn't get any response in Slack...
Any help would be appreciated...

**Comment by RaddishIoW** [comment]
I'll take a look at this too when I get a chance.

**Comment by HarelM** [comment]
The suggestion I got in the slack thread was the following:
"Cordova uses https://github.com/apache/cordova-plugin-test-framework
Not something I've really dabbled into myself (Many cordova plugins lacks native tests tbh) but it looks like it's usable for any cordova plugin, not just apache ones.... May help you provide a framework for providing a test app to serve as an environment to test the plugin."
I'm still not sure if this is helpful or not, didn't get to it yet...
