### ISSUE TITLE
Move documentation to GitHub Pages

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-plugin-background-geolocation#32]
It would be good to get the rather long README.md and other docs into a better layout, probably using GitHub pages.

The README.md should just include a quick intro, relevant details on installing and quick setup. Any further details should be broken out into their own documents.

We should make a FAQ too - there's a few things in the README.md that would make FAQ points.

**Comment by HarelM** [comment]
I agree with everything you wrote :-)
Let me know if and how I can help.
We may consider using the wiki too if github pages are annoying to maintain...
