### ISSUE TITLE
Capture in a regular basis

### ISSUE THREAD

**Issue by viniciostorres** [HaylLtd/cordova-plugin-background-geolocation#45]
Hello, Mr. Radestock,

Thanks for your work with this plugin. I am testing it in our app and it is working well.

But, it has a behavior that is inconvenient to us. When the mobile is stationary the location capture is delayed more and more.

Is possible to change it? Is there a configuration to do that? We need to capture in a regular basis, or no more than 10 minutes.

Thanks in advance.

Vinicios Torres

**Comment by HarelM** [comment]
Have you tried playing with the configuration? There's all kind of parameters that might help workaround this behavior, I think.
If this doesn't help I think the best approach would be to try and get to the bottom of this and send a PR to allow this, using some kind of switch to opt in for someone who would like to use this feature.
