### ISSUE TITLE
Cannot use the plugin in iOS

### ISSUE THREAD

**Issue by dvdpzzt-webmapp** [HaylLtd/cordova-plugin-background-geolocation#47]
**Describe the bug**
It's not really a bug but more a help request. I'm switching from the mauron plugin to this new version and managed to make it work on android. When I try to run it on iOS I'm not able to find the plugin in any variable and therefore use it. I'm quite sure I'm doing something wrong but I cannot find out why

**What I have done**
I am using Ionic v4. Since the plugin does not have the ionic-native support yet I tried to initialize it using
`declare var BackgroundGeolocation: BackgroundGeolocationPlugin;` and then using the BackgroundGeolovation variable inside my code. Unfortunately this seems to work only on android and I don't understand why it does not work in iOS. Every test I made resulted in a "cannot find function of undefined" error

**Expected behavior**
As in android I would like to have the BackgroundGeolocation global variable available to use with all the plugin functions but I cannot find it

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus Simulator
 - OS: iOS 14.5
 - Plugin version 1.1.0

**Additional context**
By the way, great work!

**Comment by dvdpzzt-webmapp** [comment]
Hello,
I am closing this since the problem was related to the cordova-ios version. Yesterday I installed the version 6 but I got some problem and did not notice I was still using the v5

Thank you anyway for the awesome job :)

**Comment by HarelM** [comment]
You scared me for a minute as I didn't fully test and verified everything in iOS platform but rather mainly in Android.
In any case, I'm glad everything works for you.
Note that ionic native guys didn't respond to my question and suggestion to update the wrapper so not much I can do there.
Having said that, the plugin JS interface now supports promises so the wrapper is almost irrelevant from my point of view...

**Comment by dvdpzzt-webmapp** [comment]
Yes, my bad :)
The first tests in the iOS simulator are really promising anyway.

Great work!
