### ISSUE TITLE
Remove legacy org.apache.http library references

### ISSUE THREAD

**Issue by RaddishIoW** [HaylLtd/cordova-plugin-background-geolocation#56]
All references to the `org.apache.http` library should be removed in favour of using `java.net.HttpURLConnection`.

**Comment by RaddishIoW** [comment]
@HarelM I'd appreciate your eyes on this at some point if you could? I've done some digging around, but it looks like the library has already been replaced in the code - it's just still listed as a dependency in the AndroidManifest.xml, Plugin.xml, etc files.
In `android/common/src/main/java/com/marianhello/bgloc/HttpPostService.java` there are no references to the apache http lib, and it uses the `java.net.HttpURLConnection` lib instead.
I'm not Android-savvy, so I could be missing something, but it looks to me like this is just a case of stale dependencies being listed. What do you think?

**Comment by HarelM** [comment]
I think you added this as part of #24 - So you'd need to remember why you added this... :-)

**Comment by HarelM** [comment]
I can't find the relevant references in the code, only stuff added as part of #24, I think the changed in #24 can be reverted...

**Comment by HarelM** [comment]
Closing as I think this is no longer relevant...

**Comment by aaadipop** [comment]
this change have conflicts with [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/bdb7af4730857a6b51662a8cfd180f6c5a3dce35/plugin.xml#L237), idk exactly if they require this line.

I locally revert #24 and looks good

**Comment by HarelM** [comment]
Feel free to submit a PR with revering of #25.
