### ISSUE TITLE
New Google Play Guidelines 

### ISSUE THREAD

**Issue by sbellver** [HaylLtd/cordova-plugin-background-geolocation#57]
Hi all

Is this solved using this repo?

https://transistorsoft.medium.com/new-google-play-console-guidelines-for-sensitive-app-permissions-d9d2f4911353

I'm from original repo (3.0.0 I think) and now Google ask about or permissions

**Comment by HarelM** [comment]
I think this is similar to this issue #19.
Please read the above issue thoroughly as it explains the difference between background and foreground (there are links to other threads there too which are important).
This plugin only supports foreground mode right now.
In most cases this is what you want and you don't need the background permission.
Having said that, I don't know what your use case is, so you might need to fork this plugin and/or send a PR in case you need something else besides what's here...

**Comment by phiasco12** [comment]
so what does this new guideline mean in terms of using this plugin?

is the app gonna get rejected?

Our app requires background location and testing this plugin, it all works fine so far!

**Comment by HarelM** [comment]
I can't summarize what's written here, you'll need to read it, sorry...

**Comment by phiasco12** [comment]
> I can't summarize what's written here, you'll need to read it, sorry...

Honestly, I just did. (twice)... its all over the place and not to the point if I'm honest.

The fact is that you've replied to the OP and said:

```
**This plugin only supports foreground mode right now.**
In most cases this is what you want and you don't need the background permission.
Having said that, I don't know what your use case is, so you might need to fork this plugin and/or send a PR in case you need something else besides what's here...
```

The plugin is called **cordova-background-geolocation-plugin**

So, either I'm missing something or something doesn't add up!

There's either a yes or a no answer to this question.

**Comment by HarelM** [comment]
Yes, you are getting this wrong.
I thought this issue is linked in #19 but apparently it isn't.
See this issue:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/688
And #19.
Look for the YouTube video.

**Comment by phiasco12** [comment]
> Yes, you are getting this wrong.
> I thought this issue is linked in #19 but apparently it isn't.
> See this issue:
> [mauron85#688](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/688)
> And #19.
> Look for the YouTube video.

Still doesn't make sense! 

The question remains.

Is the APP going to get rejected by Google if this plugin is used?!

**Comment by HarelM** [comment]
I don't know, I'm not making the decisions at Google...
I'm using this plugin in the background as a foreground service without the need to request google for permission.

This plugin doesn't support "full" background mode of operation currently.

**Comment by phiasco12** [comment]
> I don't know, I'm not making the decisions at Google... I'm using this plugin in the background as a foreground service without the need to request google for permission.
> 
> This plugin doesn't support "full" background mode of operation currently.

That's all I needed.

Thanks

**Comment by phiasco12** [comment]
> I don't know, I'm not making the decisions at Google... I'm using this plugin in the background as a foreground service without the need to request google for permission.
> 
> This plugin doesn't support "full" background mode of operation currently.

Thats all I needed.

Please slow down on the sarcasm. I never implied that you were making decisions for Google!!

I was just asking the question (as we all do) to make sure we're not going to invest hours of development using this plugin just to find out in the future that our app got rejected because of this plugin!

We're all developers trying to help each-other.
