### ISSUE TITLE
please apply this fix to IOS file /ios/common/BackgroundGeolocation/MAURConfig.m

### ISSUE THREAD

**Issue by tfelici** [HaylLtd/cordova-plugin-background-geolocation#65]
hi teams,
there is a bug in this file
 
/ios/common/BackgroundGeolocation/MAURConfig.m

which is causing incorrect permissions to be asked under IOS

please change the below lines

   if ([activityType caseInsensitiveCompare:@"AutomotiveNavigation"]) {
        return CLActivityTypeAutomotiveNavigation;
    }
    if ([activityType caseInsensitiveCompare:@"OtherNavigation"]) {
        return CLActivityTypeOtherNavigation;
    }
    if ([activityType caseInsensitiveCompare:@"Fitness"]) {
        return CLActivityTypeFitness;
    }

to

   if ([activityType caseInsensitiveCompare:@"AutomotiveNavigation"] == NSOrderedSame) {
        return CLActivityTypeAutomotiveNavigation;
    }
    if ([activityType caseInsensitiveCompare:@"OtherNavigation"] == NSOrderedSame) {
        return CLActivityTypeOtherNavigation;
    }
    if ([activityType caseInsensitiveCompare:@"Fitness"] == NSOrderedSame) {
        return CLActivityTypeFitness;
    }

**Comment by HarelM** [comment]
Thanks for takin the time to report the issue!
The best approach will be to send a PR, this way we could review it and better understand the context and issue.

**Comment by tfelici** [comment]
Hi there

the issue was reported here but never applied to the production release

https://github.com/mauron85/cordova-plugin-background-geolocation/issues/701

Kind regards

*Tom Felici*
*CEO, LambdaTek
***Direct: +44 1865 601323
Mob: +44 7748 338071
Office: +44 1865 791055
**www.lambda-tek.com <http://www.lambda-tek.com>

*Winner of the 2015 Queens Award for Enterprise
*

**Comment by HarelM** [comment]
As said before, the best path forward is to send a PR.
Thanks!

**Comment by tfelici** [comment]
apologies, I am a bit of a newbie to github - what is  PR exactly?

Kind regards

*Tom *

**Comment by HarelM** [comment]
A Pull Request -  you need to fork this repository, make the relevant code changes, make sure it works and create a PR so that we can review and merge it.

**Comment by tfelici** [comment]
I think I have done this now

can you see the PR your end?

(its my first time so bare with me :):)

Kind regards

*Tom *
**
*Winner of the 2015 Queens Award for Enterprise
*

**Comment by HarelM** [comment]
Version 2.0.3 should have this fixed. Please let me know if there's anything else that you need.

**Comment by tfelici** [comment]
Brilliant
Thank you!
I will be sure to send you any other fixes I find :)
Kind regards
Tom.

On 27 Feb 2022, 19:40, at 19:40, Harel M ***@***.***> wrote:
>Version 2.0.3 should have this fixed. Please let me know if there's
>anything else that you need.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/HaylLtd/cordova-background-geolocation-plugin/issues/65#issuecomment-1053657306
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
