### ISSUE TITLE
plugin.xml version does not match package.json version

### ISSUE THREAD

**Issue by rtholmes** [HaylLtd/cordova-plugin-background-geolocation#69]
The `version` is not consistent between `plugin.xml` and `package.json`:

https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/40098bbece618594f510dac4b0aa479ca25dfbcb/plugin.xml#L6

https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/40098bbece618594f510dac4b0aa479ca25dfbcb/package.json#L3

This causes confusion because:

```
cordova plugin list
cordova-background-geolocation-plugin 2.0.1 "CDVBackgroundGeolocation"
```
even though `2.0.3` is installed.

Similarly, the `name` field is inconsistent between the two files (likely both should be `cordova-background-geolocation-plugin`, instead of `plugin.xml` being `CDVBackgroundGeolocation`).

**Comment by HarelM** [comment]
Hmm... Bummer.
Can you make a PR to fix this and increment to 2.0.4?

**Comment by rtholmes** [comment]
@HarelM done in PR #70

**Comment by rtholmes** [comment]
One thing I noticed though is that `package-lock.json` also has a version number in there, and I'm not sure when that is supposed to be incremented.
