### ISSUE TITLE
Request permission full prompt

### ISSUE THREAD

**Issue by josuelmm** [HaylLtd/cordova-plugin-background-geolocation#71]
### Description
When making the permission request, the permission selection alert should be full prompt, like the attached image.
According to the Android documentation, two permissions must be requested at the same time for it to display the permission request that way.

https://developer.android.com/training/location/permissions#fig-approximate-only

### Platform(s)
Android

### Preferred Solution
Let the permission request come out like the image
Request ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION in a single runtime request.

<img src="https://developer.android.com/images/training/location/approximate-full-prompt.svg"  width="310px">

**Comment by HarelM** [comment]
I believe this is the case now as far as I checked and remember... But feel free to prove me wrong :-)
Not sure I understand why the dialog is not allowing these two options though...

**Comment by josuelmm** [comment]
Do you have any example of how your location permission request to come out like this?

**Comment by HarelM** [comment]
No, but I believe both permissions are requested at the same time code-wise...

**Comment by josuelmm** [comment]
Well I already checked, the code is fine. But it keeps requesting the permission in the same way, without that type of prompt, the important thing is that the geolocation works, so let's close this.
Ask the ionic and capacitor guys. They're working on Capacitor version 4. Maybe that's why too, because I'm using this with Capacitor. But I don't know the final because it doesn't come out like that. Let's close this.

**Comment by ivinantony** [comment]
Me too have the same issue in ionic 6 app. The app was crashing due to some permission issues so as @josuelmm told i asked for the physical activity and location permissions then it works fine on android 12 . But we need to give the user a popup and navigate him to give all time permission for android otherwise the app will not work after a long time in background. But I don't know what to do in android 8 and below because it doesn't have this permission

**Comment by ivinantony** [comment]
Does the app require background permission to work??? @josuelmm

**Comment by josuelmm** [comment]
Whether the app should have permissions in the background. Also check what battery profile the app has, you must remove the battery saver.
I have tested running this plugin for more than 6 hours and everything is fine.

**Comment by ivinantony** [comment]
Can you just provide an example how you done it?? @josuelmm

**Comment by ivinantony** [comment]
@josuelmm can you show me an example how you are using
