### ISSUE TITLE
Update notification while service is running

### ISSUE THREAD

**Issue by josuelmm** [HaylLtd/cordova-plugin-background-geolocation#72]
**Description**
As we well know, currently if we use the service in the background, it requires a permanent notification. It is possible that the message that one sets in the notification can be updated in real time.

I attach example images of what I need to do

<img src="https://i.imgur.com/PQVlAlT.png">
Description of images
1.- Service started, shows type of activity, time and miles traveled, with button to stop
2.- Service stopped, shows type of activity, time and miles traveled, with button to resume
3.- Service started, but the notification is minimized

**Comment by HarelM** [comment]
While updating the text dynamically is probably needed and can be generalized I'm not sure this is the case for the start/resume button...

**Comment by josuelmm** [comment]
Well if it is possible at least that the text is updated, placing the information that one wants. I want to focus it so that it shows the current time and speed, it would be great.

**Comment by josuelmm** [comment]
Does anyone have the knowledge to do this?

**Comment by HarelM** [comment]
I thought you are pushing this forward, aren't you?

**Comment by josuelmm** [comment]
I'm still looking how to do it. It is not so simple.

**Comment by josuelmm** [comment]
<img src="https://i.imgur.com/UjsnuOB.png" width="320px">
Reviewing other applications they do it in a more advanced way.
If anyone knows how to do something similar, help us.
