### ISSUE TITLE
Pluggin dont work

### ISSUE THREAD

**Issue by gusgogar** [HaylLtd/cordova-plugin-background-geolocation#73]
cordova -version 
11.0.0

Installed platforms:
  android 10.1.2

cordova-background-geolocation-plugin 2.0.4 "cordova-background-geolocation-plugin"

The program ask for permision for geolocation, but never give  a event of location.

===========================
index.js
function onDeviceReady() {
  BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: "Background tracking",
    notificationText: "enabled",
    debug: true,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    url: "http://192.168.81.15:3000/location",
    httpHeaders: {
      "X-FOO": "bar",
    },
    // customize post properties
    postTemplate: {
      lat: "@latitude",
      lon: "@longitude",
      foo: "bar", // you can also add your own properties
    },
  });

  BackgroundGeolocation.on("location", function (location) {
    // handle your locations here
    // to perform long running operation on iOS
    // you need to create background task
    console.log('localizado');
    BackgroundGeolocation.startTask(function (taskKey) {
      // execute long running task
      // eg. ajax post location
      // IMPORTANT: task has to be ended by endTask
      BackgroundGeolocation.endTask(taskKey);
    });
  });

  BackgroundGeolocation.on("stationary", function (stationaryLocation) {
    // handle stationary locations here
  });

  BackgroundGeolocation.on("error", function (error) {
    console.log(
      "[ERROR] BackgroundGeolocation error:",
      error.code,
      error.message
    );
  });

  BackgroundGeolocation.on("start", function () {
    console.log("[INFO] BackgroundGeolocation service has been started");
  });

  BackgroundGeolocation.on("stop", function () {
    console.log("[INFO] BackgroundGeolocation service has been stopped");
  });

  BackgroundGeolocation.on("authorization", function (status) {
    console.log("[INFO] BackgroundGeolocation authorization status: " + status);
    if (status !== BackgroundGeolocation.AUTHORIZED) {
      // we need to set delay or otherwise alert may not be shown
      setTimeout(function () {
        var showSettings = confirm(
          "App requires location tracking permission. Would you like to open app settings?"
        );
        if (showSettings) {
          return BackgroundGeolocation.showAppSettings();
        }
      }, 1000);
    }
  });

  BackgroundGeolocation.on("background", function () {
    console.log("[INFO] App is in background");
    // you can also reconfigure service (changes will be applied immediately)
    BackgroundGeolocation.configure({ debug: true });
  });

  BackgroundGeolocation.on("foreground", function () {
    console.log("[INFO] App is in foreground");
    BackgroundGeolocation.configure({ debug: false });
  });

  BackgroundGeolocation.on("abort_requested", function () {
    console.log("[INFO] Server responded with 285 Updates Not Required");

    // Here we can decide whether we want stop the updates or not.
    // If you've configured the server to return 285, then it means the server does not require further update.
    // So the normal thing to do here would be to `BackgroundGeolocation.stop()`.
    // But you might be counting on it to receive location updates in the UI, so you could just reconfigure and set `url` to null.
  });

  BackgroundGeolocation.on("http_authorization", () => {
    console.log("[INFO] App needs to authorize the http requests");
  });

  BackgroundGeolocation.checkStatus(function (status) {
    console.log(
      "[INFO] BackgroundGeolocation service is running",
      status.isRunning
    );
    console.log(
      "[INFO] BackgroundGeolocation services enabled",
      status.locationServicesEnabled
    );
    console.log(
      "[INFO] BackgroundGeolocation auth status: " + status.authorization
    );

    // you don't need to check status before start (this is just the example)
    if (!status.isRunning) {
      BackgroundGeolocation.start(); //triggers start on start event
    }
  });

  // you can also just start without checking for status
  // BackgroundGeolocation.start();

  // Don't forget to remove listeners at some point!

  // BackgroundGeolocation.removeAllListeners();
  console.log("Running cordova-" + cordova.platformId + "@" + cordova.version);
  document.getElementById("deviceready").classList.add("ready");

}

document.addEventListener("deviceready", onDeviceReady, false);
========================================

**Comment by HarelM** [comment]
I'm maintaining this plug in and I know it works.
Feel free to look at the plugin logs to better understand your issue.
The provided details are not organized in a manor I can read and understand...

**Comment by gusgogar** [comment]
The plugin show notificaction icon but never send location.


![Screenshot_1](https://user-images.githubusercontent.com/483606/165903632-2ff3a19f-3e1b-4f77-8726-3812e8a2c76a.png)
[app.log](https://github.com/HaylLtd/cordova-background-geolocation-plugin/files/8588988/app.log)

**Comment by HarelM** [comment]
Are you using a simulator? a real device? are you under a roof when testing it or outside moving?
If the app doesn't get location from the OS this would be the behavior I guess...

**Comment by gusgogar** [comment]
No. I'm using a real device. I am testing in a window to outside

**Comment by HarelM** [comment]
Try walking a bit outside, you are using the activity provider and that probably requires you to be active :-)

**Comment by gusgogar** [comment]
Playing with locationProvider i revice events of localizarion in javascript,  but never recive any request in  url: "http://192.168.81.15:3000/location",

**Comment by gusgogar** [comment]
Well, the plugin works. Problem was mixing http and https.
Thansk
