### ISSUE TITLE
Send data doesn't work 

### ISSUE THREAD

**Issue by Warryoz** [HaylLtd/cordova-plugin-background-geolocation#74]
Description:
I'm trying to send the coordinates to my backend in the background, but it doesn't  do anything
The background tracking works properly  but  the plugin doesn't send the coordinates with the configuration
This is my config
![image](https://user-images.githubusercontent.com/71851376/165813866-068dc732-8bff-43c2-a186-e51228e2e226.png)

This is my background subscription
![image](https://user-images.githubusercontent.com/71851376/165814024-0e6243b3-7068-47a0-9cca-366c857dfe97.png)

**Expected behavior**
Send each location to the backend even in the background

**Smartphone (please complete the following information):**
 - Huawei Y5 2019

**Additional context**
If anyone can help me, I really appreciate  it

**Comment by HarelM** [comment]
This looks similar to #58 
I personally do not post request to the server.
You can debug the code using x code or android studio to see if you get location updates on one hand and send the requests to the server on the other hand.
Feel free to send a PR if you find a bug and its solution :-)

**Comment by Warryoz** [comment]
Thank you for your answer  I really appreciate it, so I have a couple of questions for you:
1. Can I send my location by calling a service inside the subscription listener without being paused? 
like this:
![image](https://user-images.githubusercontent.com/71851376/165834925-ae887c07-44c0-44ef-ba82-cb50d888c012.png)

2. Where the locations are stored when I'm calling the getLocations method? can I use this method to send my data sometime later?

**Comment by HarelM** [comment]
You can, but note that the js code doesn't run when the app is in the background only the native code, so what I did is get all locations when the app returns from the background and use those.

**Comment by Warryoz** [comment]
Ok, I'm going to try that, thanks for your time!

**Comment by HarelM** [comment]
See here for reference:
https://github.com/IsraelHikingMap/Site/blob/2a681dd83cd34efc673208b6d508825f968d44fb/IsraelHiking.Web/src/application/services/geo-location.service.ts#L139

**Comment by Warryoz** [comment]
I've checked your repo and I have a question for you, I'm pretty new using Ionic plugins by the way and I don't know if there is a difference between using this import and the import that you use?
![image](https://user-images.githubusercontent.com/71851376/165986902-c321b0fe-bb88-4854-a5f2-3688022497d6.png)

**Comment by HarelM** [comment]
I don't know, I've created the typings for this plugin and use only them. The ionic library is referencing a parent fork of this plugin as far as I know and so I think the typings are a bit off...
