### ISSUE TITLE
Android notification

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#75]
**Describe the bug**
Remove the android notification 

**To Reproduce**
Install the app in android and set it in background. You can see a notification of the app that running in background 
**Expected behavior**
Remove this notification 

**Additional context**
I tried to startForeground value false still it shows the notification

**Comment by HarelM** [comment]
According to android guide lines you have to show the notification when the app is I'm the background.
If you wish that the GPS won't work when the app is in the background use the browser's GPS capabilities.

**Comment by ivinantony** [comment]
And this plugin is very good but i saw that app was crashing on android 12 due to some permissions issues. So i fixed by asking activity permission first and then geolocation permission. So many are facing this issue so if you could update the documentation to prevent this issue with a sample project or some instructions it will be a great help

**Comment by ivinantony** [comment]
Is there any way to open to the allow all the time permission setting instead of showing the app permission settings

**Comment by HarelM** [comment]
Hi, I'm closing this issue as I don't see an actual issue here.
I advise to read the documentation related to GPS usage, permissions etc for the android platform as the question raised here are not specific to this plugin.
