### ISSUE TITLE
Fix Android Export in AuthenticatorService

### ISSUE THREAD

**Issue by josuelmm** [HaylLtd/cordova-plugin-background-geolocation#76]
Error in Android Manifest
Add android:exported = false in com.marianhello.bgloc.sync.AuthenticatorService

`
<service
            android:exported="false"
            android:name="com.marianhello.bgloc.sync.AuthenticatorService">
            <intent-filter>
                <action android:name="android.accounts.AccountAuthenticator"/>
            </intent-filter>
            <meta-data
                android:name="android.accounts.AccountAuthenticator"
                android:resource="@xml/authenticator" />
        </service>`

**Comment by HarelM** [comment]
You don't expect a proper response to this issue, right?
You'll need to write a few more words for us to take this seriously...
