### ISSUE TITLE
Background Geolocation Tracking joins immediately to Stationary mode

### ISSUE THREAD

**Issue by Warryoz** [HaylLtd/cordova-plugin-background-geolocation#77]
**Describe the bug**
The tracking is always going to stationary mode even while I'm moving and never goes out.
**To Reproduce**
1. This is my configuration:
![image](https://user-images.githubusercontent.com/71851376/171075564-f0dacdfe-ccce-48ad-95a1-45e4d9975522.png)
I set up stationaryRadius, distanceFilter to 0  for always tracking the location
Stationary listener
![image](https://user-images.githubusercontent.com/71851376/171075649-0e14c3e4-ebbd-4f00-beec-3416dd670c08.png)
Location listener 
![image](https://user-images.githubusercontent.com/71851376/171075950-a1b4218f-12af-4d77-8921-9a7ad4a0646e.png)
While tracking is started
![stationary](https://user-images.githubusercontent.com/71851376/171075686-6e8b772f-057b-4a3f-a47c-d79fee4195d0.PNG)
**Expected behavior**
 Tracking location properly

**Smartphone (please complete the following information):**
 - Huawei Y5 2019- Android 9
 - Redmi note 9 - Android 11

I  really appreciate any help

**Comment by HarelM** [comment]
I'm not sure setting 0 in both stationary and distance filter is a good idea...
Having said that, three might be a bug here too...

**Comment by Warryoz** [comment]
I also tried stationary = 10 and distance filter 25 and the tracking behaves the same, idk why 
What do you mean with "three might be a bug here too"?

**Comment by HarelM** [comment]
Are you testing this with the simulator or outside walking?

**Comment by Warryoz** [comment]
I'm testing with outside walking and driving a car

**Comment by HarelM** [comment]
Weird... Can you share the logs from the plugin?

**Comment by Warryoz** [comment]
Do you mean these? 
![image](https://user-images.githubusercontent.com/71851376/171087736-f13379b4-01bb-42c3-9799-bbaef398e7ed.png)

**Comment by HarelM** [comment]
No, the logs the plugin stores inside. You can extract them with getLogs or something similar...

**Comment by Warryoz** [comment]
These are the logs:
I was outside walking 
![image](https://user-images.githubusercontent.com/71851376/171225366-613c1535-31b9-4ad0-9c2e-f13fba767159.png)
![image](https://user-images.githubusercontent.com/71851376/171221168-8fef46e1-5d4c-4c9f-9e54-2c79b0b536b7.png)
Starts from here

**Comment by HarelM** [comment]
I'm not sure I follow... If the distance filter is 25 meters you might get stationary events...?
In any case, my best advise is to look at the log messages, search for them in the code and better understand when they are printed to be able to debug this.
