### ISSUE TITLE
Heading and bearing undefined 

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#78]
**Describe the bug**
the app returns the value of bearing and heading as undefined  sometimes. Anyone know how to fix this  issue

**Comment by HarelM** [comment]
Are you sure this info is sent from the device's GPS?

**Comment by ivinantony** [comment]
yes. it seems not working in Samsung s21 and its gps is on. For ios more other devices sending correct data

**Comment by HarelM** [comment]
Can you share the plugin logs?

**Comment by ivinantony** [comment]
sure when i checked there is now value of heading and bearing for samsung s21 ultra and samsung s2.
![FinderAppSS](https://user-images.githubusercontent.com/66516836/171214100-3bda9ffb-ba08-4d5f-9cbb-0d616364dc0e.png)
1

**Comment by ivinantony** [comment]
sure when i checked there is now value of heading and bearing for samsung s21 ultra and samsung s2
<img width="851" alt="Screenshot 2022-05-31 at 9 18 37 PM" src="https://user-images.githubusercontent.com/66516836/171216367-47c7528f-a92b-4454-8e98-9b38cc20a85f.png">
.

**Comment by ivinantony** [comment]
Does anyone has any idea about this? It seems only in some android devices heading and bearing values are missing in the location data

**Comment by HarelM** [comment]
I would search for broader issue in Google. I believe this plugin only propagates the device GPS events.
Another thought is that when you get the position from cellular towers and not from the GPS you might get inaccurate and no heading position? It's just a thought.
Can I close this issue?

**Comment by ivinantony** [comment]
sure but when i use the provider gps i am not getting any variable of bearing and heading. and may be i can use the device orientation plugin to get the heading of the device.hope you will find a solution asap. thanks

**Comment by HarelM** [comment]
Not sure I know what solution I should be looking for... Feel free to submit a PR if you think there's a bug in the code somewhere :-)

**Comment by ivinantony** [comment]
Sure i will do that i hope this issue is only for android 12 devices

**Comment by rtcimi** [comment]
I'm getting -1 for heading and bearing on ios.

**Comment by rtcimi** [comment]
I take it back... numbers start to appearing when i've changed 0m to 1m (or more) for stationary radius and distanceFilter.
