### ISSUE TITLE
Location posting stops randomly and resumes only after switching the aeroplane mode on/off

### ISSUE THREAD

**Issue by vasdeveloper78** [HaylLtd/cordova-plugin-background-geolocation#79]
I am using the cordova-background-geolocation-plugin 2.0.4 in our Cordova 10.0 application. The issue is the location submission randomly stops after some time, and resumes only after the aeroplane mode of the device is switched on and then off.

Other JS HXR based functionalities are working fine even when the location posting is stopped.

Using Motorola Moto G41 with Android 11.

Using RAWPROVIDER with startForeground = true.
Happens when the app is in both foreground and background.

**Comment by HarelM** [comment]
Location submission to where?
Note that js code might stop running if the app is in the background due to cordova limitations.

**Comment by vasdeveloper78** [comment]
Location postings to the server.
Not using JS for location posting. Using the standard template based posting provided by the plugin. It is happening through HttpPostService.postJSON from PostLocationTask.java.

The issue mostly happens after the device leaving a weak or no signal regions.

WhatsApp location sharing works well from the same device.

I am referring XHR in my earlier post to say that the app can connect to the server through JS XHR calls while the location posting from the native side is not working.

**Comment by HarelM** [comment]
If it doesn't work at all it might be related to headers or something related to communication.
If the app stops sending sometimes it might be related to the OS killing the process to save battery.
I would recommend looking into the plugin logs and see if the plugin was stopped or something.
I personally do not use the HTTP part of this plugin so I do not test it in my app and do not know if it has issues.
My advise here is to look at the logs and the code and see if you can understand if there's an issue there.
If you find an issue please submit a PR and I'll be happy to go over it.

**Comment by ShaunBrassell** [comment]
HI vasdeveloper78, did you find a solution to this? I encountered the same issue on my Samsung S21 this weekend.

Cheers
Shaun
