### ISSUE TITLE
Error in plugin_bgloc_content_authority

### ISSUE THREAD

**Issue by DeivyPereira** [HaylLtd/cordova-plugin-background-geolocation#80]
I have a giant error that I can't do make project, when I try it, it gives me the following error:

ERROR:D:\Projects\vitarrico\vitaricoapp\android\app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:98: AAPT: error: resource string/plugin_bgloc_content_authority (aka com.venetronic.vitarrico:string/plugin_bgloc_content_authority) not found.

It is an application made in Ionic 3
Then add the plugin and try to compile with android studio and capacitor.

I will add my json package and my gradle
build.grandle

`apply plugin: 'com.android.application'
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.venetronic.vitarrico"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             // Files and dirs to omit from the packaged assets dir, modified to accommodate modern web apps.
             // Default: https://android.googlesource.com/platform/frameworks/base/+/282e181b58cf72b6ca770dc7ca5f91f135444502/tools/aapt/AaptAssets.cpp#61
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
}
apply from: 'capacitor.build.gradle'
try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.info("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}
`

package json
`{
  "name": "Vitarico",
  "version": "0.1.32",
  "author": "Venetronic",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "^8.2.10",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@auth0/angular-jwt": "1.2.0",
    "@capacitor/android": "3.3.3",
    "@capacitor/app": "1.0.7",
    "@capacitor/core": "3.3.3",
    "@capacitor/haptics": "1.1.3",
    "@capacitor/keyboard": "1.2.0",
    "@capacitor/status-bar": "1.0.6",
    "@ionic-native/android-permissions": "^4.7.0",
    "@ionic-native/background-geolocation": "^4.20.0",
    "@ionic-native/background-mode": "^4.20.0",
    "@ionic-native/barcode-scanner": "~4.17.0",
    "@ionic-native/camera": "~4.17.0",
    "@ionic-native/core": "~4.18.0",
    "@ionic-native/diagnostic": "^4.20.0",
    "@ionic-native/file": "~4.17.0",
    "@ionic-native/file-path": "~4.17.0",
    "@ionic-native/file-transfer": "~4.17.0",
    "@ionic-native/geolocation": "~4.17.0",
    "@ionic-native/onesignal": "^4.20.0",
    "@ionic-native/splash-screen": "~4.18.0",
    "@ionic-native/status-bar": "~4.18.0",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "2.2.0",
    "chart.js": "^2.7.3",
    "cordova-android": "9.1.0",
    "cordova-background-geolocation-plugin": "^1.1.0",
    "cordova-browser": "5.0.4",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova.plugins.diagnostic": "4.0.12",
    "ionic-angular": "3.9.3",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@capacitor/cli": "3.3.3",
    "@ionic/app-scripts": "^3.2.4",
    "cordova-plugin-android-permissions": "^1.1.3",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {
        "GPS_REQUIRED": "true"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-file-transfer": {},
      "onesignal-cordova-plugin": {},
      "cordova.plugins.diagnostic": {
        "ANDROID_SUPPORT_VERSION": "28.+"
      },
      "cordova-plugin-android-permissions": {}
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}
`

Can someone guide me what can I do?

**Comment by HarelM** [comment]
Using both geolocation and this plugin together is not advised.
Other than that I can't help, you'll need to debug your code and environment...

**Comment by DeivyPereira** [comment]
Any clues to get the mariahello package to work?

**Comment by itshazlan** [comment]
in my opinion, i would like to remove other geolocation plugins and using @HarelM plugin instead

**Comment by seltix5** [comment]
this appears to be related 
https://github.com/HaylLtd/cordova-background-geolocation-plugin/issues/156
