### ISSUE TITLE
Send data every 30 Seconds(or X seconds)

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#81]
**Describe the bug**
i want to sent the location data even in foreground or in background in every 30 seconds. i tried to set the Interval and fastest interval to 30000 but still the data sending before the given second. anyone have an idea to fix this?

**Comment by tepeonde** [comment]
For me the location event fires when you use the locationProvider ACTIVITY_PROVIDER. The DISTANCE_FILTER_PROVIDER works only when the devices moves the set stationaryRadius and/or distanceFilter
