### ISSUE TITLE
Not working with cordova-plugin-mobile-ocr

### ISSUE THREAD

**Issue by tepeonde** [HaylLtd/cordova-plugin-background-geolocation#84]
I try to use this plugin with the cordova-plugin-mobile-ocr plugin. I cannot get a project build or compiled event with just only these two plugins. The error messages is:

D:\Cordova\Multitrans3\platforms\android\gradlew: Command failed with exit code 1 Error output:
D:\Cordova\Multitrans3\platforms\android\app\src\main\java\com\marianhello\bgloc\data\BackgroundActivity.java:20: error: cannot access zzbfm
confidence = activity.getConfidence();
^
class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

My Environment is

    Plugin versions:
    cordova-background-geolocation-plugin 2.0.4
    cordova-plugin-mobile-ocr 3.1.2
    Platform: Android 8.x/9.x/10.x
    Cordova version: 11
    Cordova platform version (cordova platform ls): 8.1.0

Steps to Reproduce

    Create a new cordova project
    cordova plugin add https://github.com/HaylLtd/cordova-background-geolocation-plugin.git
    cordova plugin add cordova-plugin-mobile-ocr
    cordova platform add android@8
    cordova build android

I tried also android@9 and android@10 without success. Each plugin for its own do work correctly, but not both together.

Any suggestion or help is welcome.

**Comment by HarelM** [comment]
This might be related to colliding versions of Google libraries.
But there's no guarantee of plugins not breaking each other.

**Comment by tepeonde** [comment]
@HarelM thank you for your hint. Are you able and willing to help me in this case? I am willing to compensate your time and help. Thanks Sahin

**Comment by HarelM** [comment]
According to @tepeonde the following solves this incompatible google libraries versions:
Added background plugin with `--variable GOOGLE_PLAY_SERVICES_VERSION=17+`
Added the following to `app\build.grade` in dependencies section:
`implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'`
