### ISSUE TITLE
Stop the beep sound on Android

### ISSUE THREAD

**Issue by phiasco12** [HaylLtd/cordova-plugin-background-geolocation#89]
**Is your feature request related to a problem? Please describe.**

I need to be able to stop the Beep sound every time a new GPS is found.

I've tried this: debug: false,

but the app still makes a beep sound.

**Describe the solution you'd like**

Sound: false/true

**Describe alternatives you've considered**

I haven't found any.

**Comment by HarelM** [comment]
This sound is only in debug. I'm using this plugin and it didn't beep.
Please provide the configuring you use and the plugin logs.

**Comment by phiasco12** [comment]
```
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    startForeground: true,
    notificationIconColor: '#00000,
    notificationTitle: 'Background tracking',
    notificationText: 'enabled',
    debug: false,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    //url: 'https://xxxx,
    httpHeaders: {
      "Authorization": "Bearer "
    },
```

**Comment by phiasco12** [comment]
But I also found this:

```
  BackgroundGeolocation.on('background', function() {
    BackgroundGeolocation.configure({ debug: true });
  });
```


I wonder if I set that to  `BackgroundGeolocation.configure({ debug: false}); `it will stop beeping?
