### ISSUE TITLE
Plugin not working in android 12 after a long time in background or device locked

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#90]
**Describe the bug**
This plugin not working in android 12 after a long time in background .

**To Reproduce**
Install the plugin and run in an android 12 device. But if we give background permission it works but i crashes in some devices while gives the permission
**Expected behavior**
It should work both in foreground and background .

**Additional context**
Add a detailed description for the permissions which need to be given to work this plugin in android 12 and also android 9 doesn't have allow all the time permission too.so it is little bit confusing

**Comment by HarelM** [comment]
Please provide the plugin logs for this case.

**Comment by josuelmm** [comment]
Check that the battery saver is set to "no restrictions"

**Comment by ivinantony** [comment]
@josuelmm let me try this

**Comment by ivinantony** [comment]
@josuelmm can you just provide me an example of the code you have done? And also the same for the permission too. This background issue is seems in Samsung note and some android 8 devices having some permission issues. So the documentation is little bit confusing or dont have enough data about the permissions and other stuffs

**Comment by ivinantony** [comment]
Should we ask OS specific permissions ??? Does it need background permission to work for a long time in android. But Everything works fine in ios

**Comment by ivinantony** [comment]
@HarelM does this app need background location permission to working on the android 12 devices??? And the app getting crashed if we don't ask physical activity permission first.

**Comment by HarelM** [comment]
No need for background permission if you want the user to know that the app is running in the background. Use startForground to make the plugin run for long time.
This plugging doesn't support well running in the background without letting the user know - which is what this permission is all about.
Please read other issues in this repo and android tutorials to better understand this subject.

**Comment by ivinantony** [comment]
I have done this but it terminated the android after a long time

**Comment by ivinantony** [comment]
I removed custom permissions and when the plugin ask for the default permission popup and when we click on it the app is getting stuck. Its mainly happening in Samsung devices. How can i fix this issue??

**Comment by HarelM** [comment]
You'll need to debug this on your own. Sorry.
I have around 50k users and haven't got any support ticket that sounds like this issue...

**Comment by ivinantony** [comment]
For me too its facing for some users with Samsung device.let me check with a Samsung device.for working this plugin in background we don't want to give background permission right??

**Comment by HarelM** [comment]
Please try version 2.0.6. There might have been a problem with FLAG_IMMUTABLE that was fixed there...
