### ISSUE TITLE
Not getting locations in Samsung devices

### ISSUE THREAD

**Issue by ivinantony** [HaylLtd/cordova-plugin-background-geolocation#91]
**Describe the bug**
This plugin works well  in android and ios but only the issue found in samsung devices. it doesnt give any data in samsung devices.

**To Reproduce**
Install the plugin and open in samsung note 8 with android  9.
it gives the stationary location some times but not any other location.

**Expected behavior**
Should work in all the devices

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Samsung note 8 with android  9

**Additional context**

Given the battery optimization and still it doesnt work

**Comment by HarelM** [comment]
Please share the configuration and plugin logs. Otherwise I'll be forced to close this issue.

**Comment by ivinantony** [comment]
I will update it

**Comment by ivinantony** [comment]
@HarelM 
    // locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
        locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
        // locationProvider: BackgroundGeolocation.RAW_PROVIDER,
        desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
        debug: true,
        stationaryRadius: 1,
        distanceFilter: 2,
        interval: 10,
        fastestInterval: 10,
        activitiesInterval: 30,
        startForeground: true,
        notificationIconLarge: "screen",
        notificationIconSmall: "screen",



this is my configuration and i tried all the providers, and when i use activity provider and debug true it shows a popup detected Still activity but nothing else

**Comment by ivinantony** [comment]
How can debug plugin logs ?

**Comment by HarelM** [comment]
Raw provider is your best bet to see any activity.
Getting the plugin logs is done by calling getLogs (or something similar, not in front of a PC right now).
I would advise to open a GPS app to see that the GPS on the device actually sends location events...

**Comment by ivinantony** [comment]
when i check status  it says that  locationServicesEnabled  shows false in samsung devices so i enabled it in settings and now it gives stationary location but nothing else.other devices working fine. i will try to get logs right now. i tried all providers

**Comment by ivinantony** [comment]
when i check the logcat in android studio i found this @HarelM 
2022-07-09 12:44:58.890 671-671/? E/audit: type=1400 audit(1657350898.883:397990): avc:  denied  { write } for  pid=3743 comm="atrace" name="enable" dev="tracefs" ino=7036 scontext=u:r:shell:s0 tcontext=u:object_r:debugfs_tracing_debug:s0 tclass=file permissive=0 SEPF_SM-A536E_12_0001 audit_filtered
2022-07-09 12:44:58.898 3737-3737/? E/GRPC: server_chttp2.cc:40] {"created":"@1657350898.898531869","description":"No address added out of total 1 resolved","file":"external/grpc_repo/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":396,"referenced_errors":[{"created":"@1657350898.898519869","description":"Unable to configure socket","fd":3,"file":"external/grpc_repo/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1657350898.898479677","description":"Address already in use","errno":98,"file":"external/grpc_repo/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}
2022-07-09 12:44:58.899 3737-3737/? E/StudioTransport: Server failed to start. A port number wasn't bound.

**Comment by ivinantony** [comment]
this error getting with the time interval i set in the config. Anyone having a samsung device with same issue?? found in galaxy series too

**Comment by rafaellop** [comment]
@ivinantony Have you managed to fix the issue somehow? I also have Samsung (S21) and if I use the ACTIVITY_PROVIDER no events are fired. For the same configuration it is enough to switch to RAW_PROVIDER and events are properly fired. All of them.

**Comment by ivinantony** [comment]
I also not found any solution foe samsung devices. Which provider works for you??

**Comment by rafaellop** [comment]
RAW_PROVIDER works for me. Maybe @HarelM has some idea?

**Comment by HarelM** [comment]
No clue, I use raw provider and haven't heard any complains.
The following is my configuration:
https://github.com/IsraelHikingMap/Site/blob/main/IsraelHiking.Web/src/application/services/geo-location.service.ts

**Comment by rafaellop** [comment]
RAW_PROVIDER is not battery usage sensitive. @ivinantony do you maybe tried the DISTANCE_FILTER_PROVIDER?

**Comment by ivinantony** [comment]
Currently i am also using rawprovider and one user told its not working for him in samsung s20 ultra and android 12. Let me compare my configuration with @HarelM
