### ISSUE TITLE
Installation not recognized

### ISSUE THREAD

**Issue by 3rikson** [HaylLtd/cordova-plugin-background-geolocation#93]
**Describe the bug**
The Background Geolocation from Mauron85, and in the new Android versions, only returns the location of the user when in foreground, in background, it returns the last location of when was in foreground, I need to have the locations when the user uses the app in background and is moving.
I'm still no experienced, so sorry for any clear mistake that I didn't noticed.

**To Reproduce**
I uninstalled the previous version and installed this one, but even it appearing in the package.json and in the list of cordova plugins, testing in the apk it doesn't looks like returns the value.
I created a browser platform to verify the behavior, it shows that it is not installed, other plugins are recognized.
1. Uninstall the previous version of the app, and install this plugin.
![image](https://user-images.githubusercontent.com/110131692/181504558-790c0be9-f9b9-4447-8656-68405e1e2ab1.png)
![image](https://user-images.githubusercontent.com/110131692/181504780-40dd886e-e641-4ad5-88c2-cbd2c9afbc08.png)

2. I just changed the code from previous to this one, I'm still inexperienced, so not sure if this method is correct.
![image](https://user-images.githubusercontent.com/110131692/181516470-1a85c60d-7655-48f3-8264-830ae79f7091.png)

![image](https://user-images.githubusercontent.com/110131692/181507940-96ecadfa-b86b-4694-8fda-3bc0c3d801ea.png)

3. The location is sent to an API, and the values are not arriving, the inclusion of the browser was to find some info that is not possible to have when testing the apk.
![image](https://user-images.githubusercontent.com/110131692/181513208-82f2dc04-512a-42db-9d1c-8ce0e92e1deb.png)

**Expected behavior**
The location being sent to the API even in background.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/110131692/181513932-5e5c1a96-c910-4656-a10f-8b97e8c0e72a.png)

**Smartphone (please complete the following information):**
Testing on mobile with Android 11

**Comment by HarelM** [comment]
The webview stops sending events when in the background. You need to either send them to a server or get them when returning to foreground.
In either case, I'm using this plugin and it works as expected.
I'll close this issue but feel free to respond to this thread.
I also encourage you to look into other issues in this repo...

**Comment by 3rikson** [comment]
Thanks for the reply HareIM and thanks for the hard work to update the plugin.

The values are send to a server and stored in a table, those are the values that I was receiving with the previous plugin
![image](https://user-images.githubusercontent.com/110131692/181518260-6df5dc89-c9d6-4c5d-a7b2-c647d2960ea5.png)

I'll check the repo to find if people had the same issue
Best regards.
